// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjwtinerexerbsjdqvhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqd3RpbmVyZXhlcmJzamRxdmh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNzk1OTIsImV4cCI6MjA1Njc1NTU5Mn0.Ue31daa15nSsb1hnYSd1sta1pI9k2EdgsmsBJcUnWv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);